// The engine. A group is stored exactly the way a Cayley diagram stores one:
// a set of nodes, plus one arrow-map per generator.
//
// ─────────────────────────────────────────────────────────────────────────────
// THE CONVENTION, STATED ONCE, IN PUBLIC
//
// Every arrow in this codebase is RIGHT multiplication:
//
//     arrows[g][x] === "x · g"      (start at x, follow the g-arrow)
//
// This is the thing that cost us an hour on Carter's Q₄ diagram — a printed
// arrowhead can't tell you whether it means x·g or g·x, and the two give
// different answers in a non-abelian group. Here it is a line of code.
// ─────────────────────────────────────────────────────────────────────────────

// ── The vocabulary ───────────────────────────────────────────────────────────
// Each alias below names one idea. None of them add runtime safety — they are
// all `string` underneath — but each one states what kind of thing is meant.

/**
 * A member of the group — and, in diagram language, a NODE.
 *
 * "element" is the algebra word, "node"/"vertex" the graph word. Same thing.
 * Group theory and graph theory describe this object with two vocabularies and
 * textbooks switch between them without warning; they map one-to-one:
 *
 *     element  ↔  node          word     ↔  path
 *     generator ↔ arrow colour  x · y    ↔  walk from x along y's path
 *
 * Just a label: "a2", "RB", "-k". The maths does not care what it is called.
 */
export type Element = string;

/**
 * An element chosen to generate the group — one of the arrow colours.
 * The group generated by a is written ⟨a⟩.
 *
 * Deliberately an ALIAS, not a distinct type. A generator IS an element; being
 * a generator is a role it plays, not a species it belongs to. Branding this
 * so the compiler kept them apart would encode something false about groups.
 */
export type Generator = Element;

/** A route through the diagram: a sequence of generator-steps. */
export type Word = Generator[];

/**
 * Where ONE generator sends every node: perm[from] = to.
 *
 * Named Permutation because that is what it is. Right-multiplication by g is a
 * bijection on the elements — every node has exactly one g-arrow leaving it and
 * exactly one arriving. So each generator shuffles the element set.
 *
 * Worth sitting with: if every generator permutes the elements, then every row
 * of the multiplication table is a rearrangement of the element list. That is
 * the Latin square property, falling out of the type.
 */
export type Permutation = Record<Element, Element>;

/** Every element's canonical route from the identity. */
export type Words = Map<Element, Word>;

/** A filled multiplication table. table[row][col] = row · col */
export type Table = Record<Element, Record<Element, Element>>;

/**
 * A group, stored as a Cayley diagram — nothing more.
 *
 * Note what is absent: no multiplication table, no operation, no algebra.
 * The arrows are a compression of the table; everything else is derived.
 * C₅ is 5 arrows and yields 25 cells.
 */
export type Group = {
  name: string;
  elements: Element[];
  identity: Element;
  generators: Generator[];
  arrows: Record<Generator, Permutation>;

  // Human metadata. Carried through from the file; the mathematics ignores it.
  /** Other names for the SAME group — V₄ is also C₂×C₂, D₂, the Klein four-group… */
  aliases?: string[];
  notes?: string;
  source?: string;
};

// ── Derived structure ────────────────────────────────────────────────────────
//
// Everything below is derived from `arrows`, and derivation is not free:
// multiply() needs a full BFS, and table() needs n² multiplies. Recomputing
// those per call meant ~96 BFS traversals to run the checks on a FOUR-element
// group, and would have been 28,224 BFS traversals per table at order 168.
//
// So both are memoised on the group object itself, via WeakMap — the cache dies
// when the group does, no manual invalidation, no leak. This is sound because
// loaded groups are frozen (see load.ts): arrows cannot change under the cache.

const wordCache = new WeakMap<Group, Words>();
const tableCache = new WeakMap<Group, Table>();

/**
 * Give every element a WORD: the sequence of generators that walks from the
 * identity to that element. This is Carter's Definition 4.1 — "relabel each
 * node with a path that leads there from the start" — as code.
 *
 * Breadth-first, so each word is the shortest one.
 */
export function words(g: Group): Words {
  const hit = wordCache.get(g);
  if (hit) return hit;
  const computed = computeWords(g);
  wordCache.set(g, computed);
  return computed;
}

function computeWords(g: Group): Words {
  const found: Words = new Map([[g.identity, []]]);
  const queue: Element[] = [g.identity];

  while (queue.length) {
    const from = queue.shift()!;
    for (const gen of g.generators) {
      const to = g.arrows[gen]?.[from];
      if (to === undefined) throw new Error(`${g.name}: no ${gen}-arrow out of ${from}`);
      if (!found.has(to)) {
        found.set(to, [...found.get(from)!, gen]);
        queue.push(to);
      }
    }
  }
  return found;
}

/**
 * x · y, computed from arrows alone.
 *
 * y names a route from the identity — so walk that same route, but start at x.
 */
export function multiply(g: Group, x: Element, y: Element): Element {
  const path = words(g).get(y);
  if (path === undefined) throw new Error(`${g.name}: ${y} is not an element`);

  let here: Element = x;
  for (const gen of path) here = g.arrows[gen][here];
  return here;
}

/** Every product, for every ordered pair. Memoised — six checks share one build. */
export function table(g: Group): Table {
  const hit = tableCache.get(g);
  if (hit) return hit;
  const computed = computeTable(g);
  tableCache.set(g, computed);
  return computed;
}

function computeTable(g: Group): Table {
  const t: Table = {};
  for (const row of g.elements) {
    t[row] = {};
    for (const col of g.elements) t[row][col] = multiply(g, row, col);
  }
  return t;
}

/** Print a table you can eyeball against a hand-built one. */
export function printTable(g: Group): void {
  const t = table(g);
  const w = Math.max(...g.elements.map((e) => e.length)) + 2;
  const cell = (s: string) => s.padEnd(w);

  console.log(`\n${g.name}`);
  console.log(cell("·") + g.elements.map(cell).join(""));
  for (const row of g.elements) {
    console.log(cell(row) + g.elements.map((col) => cell(t[row][col])).join(""));
  }
}

// ── Structural checks. These are theorems, running as assertions. ────────────

/** Every element appears exactly once per row and per column. */
export function isLatinSquare(g: Group): boolean {
  const t = table(g);
  const complete = (xs: Element[]) => new Set(xs).size === g.elements.length;

  return g.elements.every(
    (row) =>
      complete(g.elements.map((col) => t[row][col])) &&
      complete(g.elements.map((col) => t[col][row])),
  );
}

/** Does x·y === y·x for every pair? */
export function isAbelian(g: Group): boolean {
  const t = table(g);
  return g.elements.every((x) => g.elements.every((y) => t[x][y] === t[y][x]));
}

/** Sanity: the identity really does nothing, from both sides. */
export function identityWorks(g: Group): boolean {
  const t = table(g);
  return g.elements.every((x) => t[x][g.identity] === x && t[g.identity][x] === x);
}

/** Every element has something that undoes it. */
export function everyElementHasInverse(g: Group): boolean {
  const t = table(g);
  return g.elements.every((x) => g.elements.some((y) => t[x][y] === g.identity));
}

/** Every product lands back inside the set. Nothing escapes. */
export function isClosed(g: Group): boolean {
  const t = table(g);
  const inside = new Set(g.elements);
  return g.elements.every((x) => g.elements.every((y) => inside.has(t[x][y])));
}

/**
 * (x·y)·z === x·(y·z) for all triples.
 *
 * Not automatic — it is a claim about the arrow data. Write arrows that do not
 * come from a real group and this is what catches you. O(n³), fine at this size.
 */
export function isAssociative(g: Group): boolean {
  const t = table(g);
  return g.elements.every((x) =>
    g.elements.every((y) => g.elements.every((z) => t[t[x][y]][z] === t[x][t[y][z]])),
  );
}

/** The diagonal: every element multiplied by itself. */
export function squares(g: Group): Record<Element, Element> {
  const t = table(g);
  return Object.fromEntries(g.elements.map((x) => [x, t[x][x]]));
}

/** Is every element its own inverse? (V₄ yes, C₄ no — visible as the diagonal.) */
export function allSelfInverse(g: Group): boolean {
  const sq = squares(g);
  return g.elements.every((x) => sq[x] === g.identity);
}
