// The engine. A group is stored exactly the way a Cayley diagram stores one:
// a set of nodes, plus one arrow-map per generator.
//
// ─────────────────────────────────────────────────────────────────────────────
// THE CONVENTION, STATED ONCE, IN PUBLIC
//
// Every arrow in this codebase is RIGHT multiplication:
//
//     arrows[g][x] === "x · g"      (start at x, follow the g-arrow)
//
// This exists because a printed Cayley diagram CANNOT STATE ITS OWN CONVENTION.
// An arrowhead cannot tell you whether it means x·g or g·x, the two disagree in
// any non-abelian group, and an afternoon was lost to exactly that. A drawing
// cannot say which it means. A line of code can.
// ─────────────────────────────────────────────────────────────────────────────

// ── The vocabulary ───────────────────────────────────────────────────────────
// Each alias below names one idea. None of them add runtime safety — they are
// all `string` underneath — but each one states what kind of thing is meant.

/**
 * A member of the group — and, in diagram language, a NODE.
 *
 * "element" is the algebra word, "node"/"vertex" the graph word. Same thing.
 * Group theory and graph theory describe this object with two vocabularies and
 * textbooks switch between them without warning; they map one-to-one:
 *
 *     element  ↔  node          word     ↔  path
 *     generator ↔ arrow colour  x · y    ↔  walk from x along y's path
 *
 * Just a label: "a2", "RB", "-k". The math does not care what it is called —
 * shuffle the element list and you have the same group.
 *
 * ⚑ AN ELEMENT IS A MOVE, NOT A THING BEING MOVED.
 *
 * The commonest way to misread a symmetry group, and it costs days. Two sets are
 * in play and only one of them is the group:
 *
 *     the square's 4 corners   the set being acted ON.  NOT the group.
 *     the 8 symmetries         the group. Its elements are the moves.
 *
 * D₄ has 8 elements and the square has 4 corners, so the corners cannot be the
 * elements. The sharper test is the operation: "corner 1 · corner 3" is
 * meaningless, while "rotate 90 · flip" obviously is not. Moves compose. Corners
 * do not. Only one of those two sets can be a group.
 *
 * The verb reading is an interpretation, not part of the definition — ℤ under
 * addition is a group and 5 is happily just a number. But it is ALWAYS
 * available: Cayley's theorem says every group is isomorphic to a group of
 * permutations, so the elements of any group can be viewed as actions. Same
 * Cayley as the diagrams, and not a coincidence — the diagram is a picture of
 * the group acting on itself.
 */
export type Element = string;

/**
 * An element chosen to generate the group — one of the arrow colours.
 * The group generated by a is written ⟨a⟩.
 *
 * Deliberately an ALIAS, not a distinct type. A generator IS an element; being
 * a generator is a role it plays, not a species it belongs to. Branding this
 * so the compiler kept them apart would encode something false about groups.
 */
export type Generator = Element;

/** A route through the diagram: a sequence of generator-steps. */
export type Word = Generator[];

/**
 * Where ONE generator sends every node: perm[from] = to.
 *
 * Named Permutation because that is what it is. Right-multiplication by g is a
 * bijection on the elements — every node has exactly one g-arrow leaving it and
 * exactly one arriving. So each generator shuffles the element set.
 *
 * Worth sitting with: if every generator permutes the elements, then every row
 * of the multiplication table is a rearrangement of the element list. That is
 * the Latin square property, falling out of the type.
 */
export type Permutation = Record<Element, Element>;

/** Every element's canonical route from the identity. */
export type Words = Map<Element, Word>;

/** A filled multiplication table. table[row][col] = row · col */
export type Table = Record<Element, Record<Element, Element>>;

/**
 * A group, stored as a Cayley diagram — nothing more.
 *
 * Note what is absent: no multiplication table, no operation, no algebra.
 * The arrows are a compression of the table; everything else is derived.
 * C₅ is 5 arrows and yields 25 cells.
 */
export type Group = {
  name: string;
  elements: Element[];
  identity: Element;
  generators: Generator[];
  arrows: Record<Generator, Permutation>;

  // Human metadata. Carried through from the file; the mathematics ignores it.
  /** Other names for the SAME group — V₄ is also C₂×C₂, D₂, the Klein four-group… */
  aliases?: string[];
  notes?: string;
  source?: string;
};

// ── Derived structure ────────────────────────────────────────────────────────
//
// Everything below is derived from `arrows`, and derivation is not free:
// multiply() needs a full BFS, and table() needs n² multiplies. Recomputing
// those per call meant ~96 BFS traversals to run the checks on a FOUR-element
// group, and would have been 28,224 BFS traversals per table at order 168.
//
// So both are memoised on the group object itself, via WeakMap — the cache dies
// when the group does, no manual invalidation, no leak. This is sound because
// loaded groups are frozen (see load.ts): arrows cannot change under the cache.

const wordCache = new WeakMap<Group, Words>();
const tableCache = new WeakMap<Group, Table>();

/**
 * Give every element a WORD: the sequence of generators that walks from the
 * identity to that element. This is Carter's Definition 4.1 — "relabel each
 * node with a path that leads there from the start" — as code.
 *
 * Breadth-first, so each word is the shortest one.
 */
export function words(g: Group): Words {
  const hit = wordCache.get(g);
  if (hit) return hit;
  const computed = computeWords(g);
  wordCache.set(g, computed);
  return computed;
}

function computeWords(g: Group): Words {
  const found: Words = new Map([[g.identity, []]]);
  const queue: Element[] = [g.identity];

  while (queue.length) {
    const from = queue.shift()!;
    for (const gen of g.generators) {
      const to = g.arrows[gen]?.[from];
      if (to === undefined) throw new Error(`${g.name}: no ${gen}-arrow out of ${from}`);
      if (!found.has(to)) {
        found.set(to, [...found.get(from)!, gen]);
        queue.push(to);
      }
    }
  }
  return found;
}

/**
 * x · y, computed from arrows alone.
 *
 * ⚑ Two different claims, worth keeping apart:
 *
 *   WHAT IT IS         the group's binary operation. Combine two elements, get
 *                      a third. In move-language: do x, THEN do y. This is an
 *                      axiom — a group has an operation, by definition.
 *
 *   HOW THIS COMPUTES  express y as a word, then walk that word starting from x
 *                      instead of from the identity.
 *
 * The second only works because the arrows encode the first. Arrows are a
 * REPRESENTATION of the operation; the operation exists whether or not anybody
 * draws it. Confusing the mechanism for the meaning is how people end up
 * believing a group IS its diagram.
 *
 * Note also that the answer does not depend on WHICH word names y. In V₄, "RB"
 * can be reached as R·B or as B·R, and both give identical products throughout
 * the table. That path-independence is not luck — it is associativity, and it is
 * precisely what makes the thing a group. Feed this function arrows that are not
 * a group and the two routes start to disagree.
 */
export function multiply(g: Group, x: Element, y: Element): Element {
  const path = words(g).get(y);
  if (path === undefined) throw new Error(`${g.name}: ${y} is not an element`);

  let here: Element = x;
  for (const gen of path) here = g.arrows[gen][here];
  return here;
}

/** Every product, for every ordered pair. Memoised — six checks share one build. */
export function table(g: Group): Table {
  const hit = tableCache.get(g);
  if (hit) return hit;
  const computed = computeTable(g);
  tableCache.set(g, computed);
  return computed;
}

function computeTable(g: Group): Table {
  const t: Table = {};
  for (const row of g.elements) {
    t[row] = {};
    for (const col of g.elements) t[row][col] = multiply(g, row, col);
  }
  return t;
}

/** Print a table you can eyeball against a hand-built one. */
export function printTable(g: Group): void {
  const t = table(g);
  const w = Math.max(...g.elements.map((e) => e.length)) + 2;
  const cell = (s: string) => s.padEnd(w);

  console.log(`\n${g.name}`);
  console.log(cell("·") + g.elements.map(cell).join(""));
  for (const row of g.elements) {
    console.log(cell(row) + g.elements.map((col) => cell(t[row][col])).join(""));
  }
}

// ── Structural checks: the axioms and their consequences, as running code ────
//
// Each carries its formal statement, then the same thing in English. The symbols
// are worth reading rather than skipping — they say exactly what the code says,
// more compactly, and the correspondence is close to mechanical:
//
//     ∀   for all          →  .every()
//     ∃   there exists     →  .some()
//     ∈   is a member of   →  the element list / a Set
//     G   the group        →  g.elements
//     e   the identity     →  g.identity
//     xy  x times y        →  t[x][y]     (juxtaposition means the operation)
//
// Four of these are the GROUP AXIOMS — closure, identity, inverses,
// associativity. The rest are consequences or distinguishing properties.

/**
 * ∀a,b ∈ G, ∃! x ∈ G :  ax = b     and     ∃! y ∈ G :  ya = b
 *
 *   "for all a and b in G, there is exactly ONE x solving ax = b,
 *    and exactly one y solving ya = b"
 *
 * The ∃! means "there exists a unique". Every equation has exactly one answer —
 * which, laid out as a grid, is the statement that every element appears exactly
 * once in each row and each column. Hence "Latin square".
 *
 * NOT an axiom. It is a CONSEQUENCE of inverses existing: if ax = b then
 * x = a⁻¹b, and that is the only possibility. Carter flags this in the very
 * paragraph before Definition 4.2 — "the impact of this fact on the appearance
 * of multiplication tables", where "this fact" is that every element has an
 * inverse.
 *
 * ⚠ The converse is false: every group table is a Latin square, but not every
 * Latin square is a group table. Latin squares can fail associativity.
 */
export function isLatinSquare(g: Group): boolean {
  const t = table(g);
  const complete = (xs: Element[]) => new Set(xs).size === g.elements.length;

  return g.elements.every(
    (row) =>
      complete(g.elements.map((col) => t[row][col])) &&
      complete(g.elements.map((col) => t[col][row])),
  );
}

/**
 * ∀x,y ∈ G :  xy = yx
 *
 *   "for all x and y in G, x times y equals y times x"
 *
 * NOT an axiom — plenty of real groups fail it. A group that satisfies it is
 * called ABELIAN, after Niels Henrik Abel. C₄ and V₄ are; D₄ and Q₈ are not.
 *
 * Compare the shape of this with isAssociative below. Here the ELEMENTS swap
 * places. There the BRACKETS move and the elements stay put. Two different
 * claims that are easy to confuse precisely because the code looks similar.
 */
export function isAbelian(g: Group): boolean {
  const t = table(g);
  return g.elements.every((x) => g.elements.every((y) => t[x][y] === t[y][x]));
}

/**
 * ∃e ∈ G, ∀x ∈ G :  xe = ex = x        ← AXIOM
 *
 *   "there is an e in G such that for every x, x times e and e times x
 *    both give back x"
 *
 * Both sides are checked, and in a non-abelian group that matters: nothing
 * guarantees that something acting as an identity from the right also does so
 * from the left. (For groups they must coincide — but that is a small theorem,
 * not something to assume while validating data that may not be a group.)
 *
 * Note the ∃ sits OUTSIDE the ∀ here: one identity works for every element. In
 * everyElementHasInverse below the quantifiers are the other way round, and that
 * ordering is the whole difference between the two axioms.
 */
export function identityWorks(g: Group): boolean {
  const t = table(g);
  return g.elements.every((x) => t[x][g.identity] === x && t[g.identity][x] === x);
}

/**
 * ∀x ∈ G, ∃y ∈ G :  xy = e             ← AXIOM
 *
 *   "for every x in G, there EXISTS a y in G with x times y equal to
 *    the identity"
 *
 * That y is written x⁻¹ and called the inverse of x.
 *
 * ⚑ The only ∃ in this file, and the only .some(). Every other check is ∀ all
 * the way down. You do not need everything to undo x — you need ONE thing to
 * exist. Swap .some() for .every() and you would be claiming everything undoes
 * everything, which is false in any group bigger than order 2.
 *
 * And note the quantifier ORDER against identityWorks: there ∃ came first (one
 * identity serves all), here ∀ comes first (each x gets its own inverse). Same
 * two symbols, opposite meaning.
 */
/**
 * x⁻¹ — the element that undoes x.
 *
 * ∃! y ∈ G :  xy = yx = e
 *
 *   "there is exactly ONE y with x times y, and y times x, both giving e"
 *
 * The uniqueness is not an extra assumption — it follows from associativity.
 * If y and z both invert x then
 *
 *     y = y·e = y·(x·z) = (y·x)·z = e·z = z
 *              └──────────┬──────────┘
 *                   associativity
 *
 * which is part of why associativity is an axiom rather than a convenience:
 * without it an element could have several different undos.
 *
 * Three ways to compute this, and the choice is not obvious:
 *
 *   1. SEARCH THE ROW      find the y with t[x][y] === e.  O(n), always works.
 *   2. BACKWARDS ONE ARROW which node's g-arrow lands on e? O(n), but only for
 *                          a generator — its word is one step long.
 *   3. AS A POWER          x⁻¹ = x^(order(x) − 1), since x^order = e.
 *                          This is "in a finite group you never need a reverse
 *                          gear" as a formula: going forward far enough IS
 *                          going backward.
 *
 * Row search is used here — simplest, and the table is memoised anyway. Method
 * 3 would matter if the table were ever too large to build.
 */
export function inverse(g: Group, x: Element): Element {
  const t = table(g);
  const y = g.elements.find((cand) => t[x][cand] === g.identity);
  if (y === undefined) throw new Error(`${g.name}: ${x} has no inverse — not a group`);
  return y;
}

/** Every element's inverse, in one pass. */
export function inverses(g: Group): Record<Element, Element> {
  return Object.fromEntries(g.elements.map((x) => [x, inverse(g, x)]));
}

export function everyElementHasInverse(g: Group): boolean {
  const t = table(g);
  return g.elements.every((x) => g.elements.some((y) => t[x][y] === g.identity));
}

/**
 * ∀x,y ∈ G :  xy ∈ G                   ← AXIOM
 *
 *   "for all x and y in G, their product is also in G"
 *
 * ⚑ This cannot fail for any group that loaded, and that is worth understanding
 * rather than deleting.
 *
 * multiply() only ever assigns `here` from two sources: the caller's element, or
 * g.arrows[gen][here]. And phase 3 of validation already proved every arrow
 * target is an element. So a product has nowhere else to land — the type
 * Permutation = Record<Element, Element> says as much in its signature.
 *
 * The interesting consequence: choosing arrows as the representation turns an
 * AXIOM into a STRUCTURAL GUARANTEE. Represent a group by a formula instead and
 * closure becomes something you must check. Represent it as a diagram and it
 * comes free, because an arrow can only point at a node.
 *
 * Kept as cheap insurance for raw objects that skipped the loader, and because
 * it documents the axiom.
 */
export function isClosed(g: Group): boolean {
  const t = table(g);
  const inside = new Set(g.elements);
  return g.elements.every((x) => g.elements.every((y) => inside.has(t[x][y])));
}

/**
 * ∀x,y,z ∈ G :  (xy)z = x(yz)          ← AXIOM
 *
 *   "for all x, y and z in G, multiplying x·y first gives the same answer
 *    as multiplying y·z first"
 *
 * ⚑ The elements do NOT move. x, y and z stay in that order in both expressions.
 * Only the BRACKETS move. That is the whole difference from commutativity, where
 * the elements swap and the brackets are irrelevant:
 *
 *     abelian       xy = yx           elements swapped
 *     associative   (xy)z = x(yz)     brackets moved
 *
 * Unlike closure, this can genuinely fail on well-formed arrows — it is a real
 * claim about the data, and it is what catches arrow sets that are permutations
 * and reach everything but still are not a group.
 *
 * O(n³): the only triple loop here. 4.7M comparisons at order 168, which is why
 * textbooks state associativity rather than verify it, and why it is flagged in
 * the roadmap for large groups.
 */
export function isAssociative(g: Group): boolean {
  const t = table(g);
  return g.elements.every((x) =>
    g.elements.every((y) => g.elements.every((z) => t[t[x][y]][z] === t[x][t[y][z]])),
  );
}

/**
 * x ↦ x²   for each x ∈ G
 *
 *   "map each x to x times itself"
 *
 * The main diagonal of the multiplication table. Not a property, just a view —
 * but a revealing one. V₄'s diagonal is all identity; C₄'s is not, and that
 * single glance distinguishes two groups of the same order.
 */
export function squares(g: Group): Record<Element, Element> {
  const t = table(g);
  return Object.fromEntries(g.elements.map((x) => [x, t[x][x]]));
}

/**
 * ∀x ∈ G :  x² = e        equivalently   ∀x ∈ G :  x = x⁻¹
 *
 *   "for all x in G, x times itself is the identity"
 *   — that is, everything is its own undo
 *
 * NOT an axiom. True in V₄, false in C₄, and the cleanest way to tell those two
 * apart. Visible instantly as a diagonal of pure identity.
 *
 * A group with this property is necessarily abelian, and is a direct product of
 * copies of C₂ — which is exactly why V₄ is also written C₂ × C₂. Two switches.
 */
export function allSelfInverse(g: Group): boolean {
  const sq = squares(g);
  return g.elements.every((x) => sq[x] === g.identity);
}
